# DATA
classes: 16
modality: CT

# MODEL
arch: attention_unet  
spatial_dims: 2       
in_channels: 1        
out_channels: 16
channels: [64, 128, 256, 512, 1024] 
strides: [2, 2, 2, 2]
kernel_size: 3       
up_kernel_size: 3
dropout: 0.0

# TRAIN
epochs: 100       
roi_size: [512, 512] 
batch_size: 32
start_epoch: 0
num_workers: 24
aug_device: 'cpu'

split_seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.0001       
weight_decay: 0.05
weight: [0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
rlt: 1

# AUGMENTATION
scale: [0.8, 1.2] 
rotate: 30 
translate: [0.1, 0.1] 
gaussian_noise_std: 0.02
additive_brightness_std: 0.7 
gamma_range: [0.5, 1.6]

print_freq: 10
iter_per_epoch: 200 

# VALIDATION
ema: True
ema_alpha: 0.99
val_freq: 10

# INFERENCE
sliding_window: False 
window_size: [512, 512] 

# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000'
dist_backend: "nccl" 
multiprocessing_distributed: false
reproduce_seed: 2023