classes: 16
modality: CT
arch: unetrpp
spatial_dims: 3
in_channels: 1
out_channels: 16
feature_size: 16
hidden_size: 256
num_heads: 4
pos_embed: "perceptron"
norm_name: "instance"
dropout_rate: 0.0
depths: [3, 3, 3, 3]
dims: [32, 64, 128, 256]
do_ds: False
epochs: 100
roi_size: [16, 160, 160]
batch_size: 1
start_epoch: 0
num_workers: 8
aug_device: 'cpu'
split_seed: 0
k_fold: 5
optimizer: adamw
base_lr: 0.0001
weight_decay: 0.05
weight: [0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
rlt: 1
scale: [0.8, 1.2]
rotate: 30
translate: [0.1, 0.1]
gaussian_noise_std: 0.02
additive_brightness_std: 0.7
gamma_range: [0.5, 1.6]
print_freq: 10
iter_per_epoch: 200
ema: True
ema_alpha: 0.99
val_freq: 10
sliding_window: True
window_size: [16, 160, 160]
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000'
dist_backend: "nccl"
multiprocessing_distributed: false
reproduce_seed: 2023